QF-663 Employer feedback new function execute summaries
SkillsFundingAgency/das-provide-feedback-employer pull request #129
Opened 2022-10-07 15:00 UTC by ianatesfa

2022-10-10 07:48 UTC, CodeWolf86 requested changes

2022-10-10 07:48 UTC, CodeWolf86 commented on src/Employer/ESFA.DAS.ProvideFeedback.Employer.Application/FeedbackSummariesService.cs
> +            await _dbRepository.GenerateProviderRatingResults(_settings.AllUsersFeedback, _settings.ResultsForAllTime, _settings.RecentFeedbackMonths, toleranceParsedOk ? tolerance : 0);
I think we can get away with making these a Task.WaitAll rather than sequential?

2022-10-10 07:48 UTC, CodeWolf86 commented on src/Employer/ESFA.DAS.ProvideFeedback.Employer.Functions.Emailer/GenerateFeedbackSummariesFunction.cs
> +        //public async Task Run([TimerTrigger("0 0 */3 * * *", RunOnStartup = false)] TimerInfo myTimer, ILogger log)
Did you mean to switch these two timer signatures around so one isn't on start up?

2022-10-10 07:49 UTC, CodeWolf86 requested changes

2022-10-10 07:49 UTC, CodeWolf86 commented on azure/template.json
> +        "employerFeedbackSettingsResultsForAllTime": {
Now you've made these ARM changes, can you try deploying this branch to AT to see if it all deploys correctly?

2022-10-10 14:11 UTC, ianatesfa commented on src/Employer/ESFA.DAS.ProvideFeedback.Employer.Application/FeedbackSummariesService.cs
> +            await _dbRepository.GenerateProviderRatingResults(_settings.AllUsersFeedback, _settings.ResultsForAllTime, _settings.RecentFeedbackMonths, toleranceParsedOk ? tolerance : 0);
OK, done

2022-10-11 09:05 UTC, CodeWolf86 approved these changes

2022-10-11 09:05 UTC, merged