QF-1100-DecommissionEmailDeleting
SkillsFundingAgency/das-provide-feedback-employer pull request #138
Opened 2022-12-02 16:02 UTC by SarahDuncan

2022-12-08 16:23 UTC, CodeWolf86 approved these changes

2023-01-04 16:09 UTC, SawNawDfE commented on src/Employer/ESFA.DAS.EmployerProvideFeedback/Services/TrainingProviderService.cs
>              // Augment the provider records with feedback data. Urgh.
I remember seeing quite a lot of new comments in this branch that might have been used as signposts. Those should be removed before this is merged

2023-01-04 16:13 UTC, SawNawDfE commented on src/Employer/ESFA.DAS.EmployerProvideFeedback/Infrastructure/EnsureFeedbackNotSubmitted.cs
> +                var employerEmailDetail = _employerEmailDetailRepository.GetEmployerAccountIdFromUniqueSurveyCode(uniqueCode).GetAwaiter().GetResult();
Good spot, there might be other instances where the name needs to be changed to match the new method call

2023-01-05 10:46 UTC, SawNawDfE requested changes

2023-01-05 10:46 UTC, SawNawDfE commented on src/Employer/UnitTests/EmployerProvideFeedback/Controllers/HomeControllerTests.cs
>          public HomeControllerTests()
While we're in here, there are a couple of things we could do to scout and clean-up.

A constructor in a test class performs a _test setup_, which has come to be recognised as bad practice. In the past, xUnit used to officially support setups via the `SetUp` attribute; they have removed this. Microsoft advises against it in their [unit testing best practices](https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices). 

There are several reasons:

- since the setup is done prior to every test, it's easy to setup too much or too little
- not all tests in a test class might need the same shared state
- a test is harder to follow when some of its logic lives inside shared state
- in some cases we might want to run a large number of tests in parallel, and this is much easier when the tests don't share any state

We can improve these tests by moving all the object creation and mocking to helper classes.

The biggest offender is `employerEmailDetailsRepoMock`. It is initialised on line 37, used on line 49, mutated on line 58, then mutated _again_ in another test! We can improve this by having a method `GetMockEmployerEmailDetailsRepo()` that initialises the mock, sets up in the mock, and returns it. All the tests can use this mock, except the one on line 77 which performs its own setup.

The `_controller` can be created in a method that takes some of the mocked objects created in other methods.

You don't have to do it exactly this way, as long as the end goal of removing test setups from the constructor is achieved.

2023-01-05 10:55 UTC, SawNawDfE requested changes

2023-01-05 10:55 UTC, SawNawDfE commented on src/Employer/UnitTests/EmployerProvideFeedback/Controllers/HomeControllerTests.cs
> +        private readonly int _mockAccountId;
This `int` is declared as a field, initialised to its default value of zero, then used in only one place. We can delete this and simply use 0 in the one place that it's used.

2023-02-08 10:37 UTC, SarahDuncan commented on src/Employer/ESFA.DAS.EmployerProvideFeedback/Services/TrainingProviderService.cs
>              // Augment the provider records with feedback data. Urgh.
This was in the original code before I changed it - still want it removed?

2023-02-08 10:39 UTC, SarahDuncan commented on src/Employer/ESFA.DAS.EmployerProvideFeedback/Services/TrainingProviderService.cs
> -            // Select all
These were all here before I changed the code - still want them removed?

2023-02-08 10:51 UTC, SawNawDfE commented on src/Employer/ESFA.DAS.EmployerProvideFeedback/Services/TrainingProviderService.cs
>              // Augment the provider records with feedback data. Urgh.
I know you didn't add those comments. Generally speaking, comments like this should not make it into production code

2023-02-08 10:53 UTC, SawNawDfE commented on src/Employer/ESFA.DAS.EmployerProvideFeedback/Services/TrainingProviderService.cs
> -            // Select all
I know you didn't add those comments. Generally speaking, comments like this should not make it into production code

2023-02-08 10:57 UTC, SarahDuncan commented on src/Employer/UnitTests/EmployerProvideFeedback/Controllers/HomeControllerTests.cs
> +        private readonly int _mockAccountId;
@SawNawDfE does `new int()` just  set the variable to 0?

2023-02-08 11:22 UTC, SarahDuncan commented on src/Employer/ESFA.DAS.EmployerProvideFeedback/Infrastructure/EnsureFeedbackNotSubmitted.cs
> +                var employerEmailDetail = _employerEmailDetailRepository.GetEmployerAccountIdFromUniqueSurveyCode(uniqueCode).GetAwaiter().GetResult();
done

2023-02-08 11:22 UTC, SarahDuncan commented on src/Employer/ESFA.DAS.EmployerProvideFeedback/Orchestrators/ReviewAnswersOrchestrator.cs
> +                Guid? uniqueSurveyCode = await _employerFeedbackRepository.GetUniqueSurveyCodeFromFeedbackId(feedbackId);
done

2023-02-08 11:22 UTC, SarahDuncan commented on src/Employer/ESFA.DAS.EmployerFeedbackEmail.Data/Repositories/EmployerFeedbackRepository.cs
>          private int _commandTimeoutSeconds = 120;
done

2023-02-08 11:53 UTC, SarahDuncan commented on src/Employer/ESFA.DAS.EmployerProvideFeedback/Services/TrainingProviderService.cs
>              // Augment the provider records with feedback data. Urgh.
done

2023-02-08 11:53 UTC, SarahDuncan commented on src/Employer/ESFA.DAS.EmployerProvideFeedback/Services/TrainingProviderService.cs
> -            // Select all
done

2023-02-08 12:10 UTC, SawNawDfE commented on src/Employer/UnitTests/EmployerProvideFeedback/Controllers/HomeControllerTests.cs
> +        private readonly int _mockAccountId;
I think so, that's what this answer says: https://stackoverflow.com/questions/13171537/difference-between-0-and-new-int-in-c-sharp

Not sure why we'd do that, though. An integer always needs a value, so it's best to explicitly assign that value. And if that assigned value never changes, it makes sense to declare it as a constant

2023-02-08 12:43 UTC, SawNawDfE commented on src/Employer/UnitTests/EmployerProvideFeedback/Controllers/HomeControllerTests.cs
>          public HomeControllerTests()
Feel free to leave this for now if it's too much :)

2023-02-08 14:11 UTC, SawNawDfE commented on src/Employer/ESFA.DAS.EmployerFeedbackEmail.Data/Repositories/EmployerFeedbackRepository.cs
>          private int _commandTimeoutSeconds = 120;
It's showing as unchanged to me

2023-02-08 14:16 UTC, SarahDuncan commented on src/Employer/UnitTests/EmployerProvideFeedback/Controllers/HomeControllerTests.cs
> +        private readonly int _mockAccountId;
done

2023-02-08 14:17 UTC, SarahDuncan commented on src/Employer/UnitTests/EmployerProvideFeedback/Controllers/HomeControllerTests.cs
>          public HomeControllerTests()
done

2023-02-08 14:19 UTC, SawNawDfE commented on src/Employer/ESFA.DAS.EmployerFeedbackEmail.Data/Repositories/EmployerFeedbackRepository.cs
> +        const int CommandTimeoutSeconds = 120;
The `private` modifier can remain. Member variables are private by default, but it's good to be explicit
```suggestion
        private const int CommandTimeoutSeconds = 120;
```

2023-02-08 14:30 UTC, SawNawDfE commented on src/Employer/UnitTests/EmployerProvideFeedback/Controllers/HomeControllerTests.cs
> +            return _context;
For brevity, this can become one statement without the variable declaration:
```suggestion
            return new DefaultHttpContext()
            {
                User = new ClaimsPrincipal(new ClaimsIdentity(new Claim[]
                {
                    new Claim(ClaimTypes.NameIdentifier, GetSurveyModel().UserRef.ToString()),
                }))
            };
```

2023-02-08 14:31 UTC, SawNawDfE commented on src/Employer/UnitTests/EmployerProvideFeedback/Controllers/HomeControllerTests.cs
> +            return _surveyModel;
This can also be one-lined:
```suggestion
            return new SurveyModel()
            {
                UserRef = Guid.NewGuid()
            };
```

2023-02-08 14:33 UTC, SawNawDfE commented on src/Employer/UnitTests/EmployerProvideFeedback/Controllers/HomeControllerTests.cs
> +            return _employerEmailDetailsRepoMock;
This and two other similar methods can be one-lined without the declaration, after which you might decide that it's not worth making an entire method to house one line of code

2023-02-08 15:47 UTC, SarahDuncan commented on src/Employer/ESFA.DAS.EmployerFeedbackEmail.Data/Repositories/EmployerFeedbackRepository.cs
> +        const int CommandTimeoutSeconds = 120;
done

2023-02-08 15:49 UTC, SarahDuncan commented on src/Employer/UnitTests/EmployerProvideFeedback/Controllers/HomeControllerTests.cs
> +            return _context;
done

2023-02-08 15:50 UTC, SarahDuncan commented on src/Employer/UnitTests/EmployerProvideFeedback/Controllers/HomeControllerTests.cs
> +            return _surveyModel;
done

2023-02-08 15:53 UTC, SarahDuncan commented on src/Employer/UnitTests/EmployerProvideFeedback/Controllers/HomeControllerTests.cs
> +            return _employerEmailDetailsRepoMock;
done

2023-02-09 17:25 UTC, closed without merging